// module.exports = {
//     legacybaseurl: "http://alphagensoa.koovs.com",
//     poApiUrl: "http://52.172.182.183:9048",
//     asnApiUrl: "http://52.172.182.183:9047",
//     imageUrl: "https://alpha-images-brandfactory.s3-ap-southeast-1.amazonaws.com",
//     cookiePrefix: "alpha",
//     accessTokenCookie: "AccessToken",
//     refreshTokenCookie: "RefreshToken",
//     cookieExpiryDays: "180",
//     config: {
//       bucketName: "alpha-images-brandfactory",
//       sizeMapBucketName: "alpha-images-brandfactory/sizeguide",
//       region: "ap-southeast-1",
//       accessKeyId: "AKIAXYOIZ263CGJGLM56",
//       secretAccessKey: "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"
//     },
    
//     localApiUrl: "http://18.136.23.209:9096",
//     shippingChargesServiceApiUrl: "http://18.136.23.209:9191",
//     requestTimeoutKey: {
//       DEFAULT: 15000,
//       GET: 15000,
//       POST: 15000,
//       PUT: 15000,
//       DELETE: 15000,
//       GETUSERPROFILE: 15000
//     },
//     asnApiCredential: {
//       username: "websvc",
//       password: "579g2J*48kds3cr31"
//     },
//     authApiBaseUrl: "http://alpha-auth.brandfactoryonline.com",
//     env: "local",
//     recordMessage: "No Record Found",
//     taggingDevApi: "http://192.168.3.177:9096",
//     orderApiUrl: "http://alpha-api.brandfactoryonline.com",
//     ruleServiceApiUrl: "http://alpha-api.brandfactoryonline.com",
//     baseUrl: "http://alpha-catalog.brandfactoryonline.com",
//     pricingApiUrl: "http://spring.alphagen-internal:9098",
//     inventoryApiUrl: "http://spring.alphagen-internal:9093",
//     vmApiDomain: "http://13.233.223.188",
//     vendorId: "KOOVS",
//     bsid: "e9fe04a841f5341698038b9d00a27fe7",
//     namespace: "koovs",
//     NewruleServiceApiUrl: "http://18.136.23.209:9191",
//     PincodeServiceApiUrl: "http://18.136.23.209:9092",
//     HomeServiceApiUrl : "http://alpha-api.brandfactoryonline.com",
//     storeApiUrl : "http://alpha-api.brandfactoryonline.com",
//     synonymsApi:"http://18.136.23.209:9094"
//   };
  
// module.exports = {
//   ReferralApiUrl : "/jarvis-home-service/internal/v1/home/",
//   courierServiceApiUrl: "http://a7c6a5e4a719e11e9b89502bb79d7e19-952630164.ap-southeast-1.elb.amazonaws.com:32510",
//   poApiUrl: "http://52.172.182.183:9048",
//   asnApiUrl: "http://52.172.182.183:9047",
//   localApiUrl:"https://api-mtmigration.koovs.tech",
//   imageUrl: "https://s3-ap-southeast-1.amazonaws.com/img.koovs.com",
//   cookiePrefix: "koovs",
//   config: {
//     bucketName: "img.koovs.com",
//     sizeMapBucketName: "koovsimages/sizeguide",
//     videoBucketName: "videos.koovs.cos3configm/catwalk",
//     region: "ap-southeast-1",
//     accessKeyId: "AKIAI5KORQD45VHUZJGQ",
//     secretAccessKey: "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"
//   },
//   s3config: {
//     bucketName: "img.koovs.com",
//     region: "ap-southeast-1",
//     accessKeyId: "AKIAWJMHT5ACVSF2E2BJ",
//     secretAccessKey: "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"
// },
//   accessTokenCookie: "AccessToken",
//   refreshTokenCookie: "RefreshToken",
//   cookieExpiryDays: "180",
//   requestTimeoutKey: {
//     DEFAULT: 15000,
//     GET: 15000,
//     POST: 15000,
//     PUT: 15000,
//     DELETE: 15000,
//     GETUSERPROFILE: 15000
//   },
//   authApiBaseUrl: "https://api-mtmigration.koovs.tech",
//   env: "local",
//   recordMessage: "No Record Found",
//   taggingDevApi: "https://api-mtmigration.koovs.tech",
//   orderApiUrl: "https://api-mtmigration.koovs.tech",
//   ruleServiceApiUrl: "https://api-mtmigration.koovs.tech",
//   NewruleServiceApiUrl : "https://api-mtmigration.koovs.tech",
//   notificationApiUrl:"https://api-mtmigration.koovs.tech",
//   baseUrl: "http://migration.koovs.com",
//   pricingApiUrl: "https://api-mtmigration.koovs.tech",
//   //inventoryApiUrl: "http://13.228.158.178:9093",
//   inventoryApiUrl: "https://api-mtmigration.koovs.tech",
//   vmApiDomain: "http://13.233.223.188",
//   vendorId: "KOOVS",
//   bsid: "e9fe04a841f5341698038b9d00a27fe7",
//   courierApiUrl: "https://api-mtmigration.koovs.tech",
//   namespace: "koovs",
//   PincodeServiceApiUrl: "https://api-mtmigration.koovs.tech",
//   HomeServiceApiUrl: "https://api-mtmigration.koovs.tech",
//   cdnUrl: "https://api-mtmigration.koovs.tech/",
//   jarvisListingUrl: "/jarvis-service/v1/product/listing?href=",
//   APP_MAIL_LINK: "http://migration.koovs.com",
//   WEB_MAIL_LINK: "http://migration.koovs.com",
//   FROM_EMAIL: "support@koovs.com",
//   IOS_DEEP_LINK: "koovs",
//   newSearchService:"http://search-service-external.koovs.com:30353",
//   ALLOWED_EMAIL_DOMAINS: /^\"?[\w-_\.]*\"?@koovs\.com$/,
//   reportconfig: {
//       bucketName: "data-dumps-analysis",
//       region: "ap-southeast-1",
//       accessKeyId: "AKIAYYR5X4KOSK7ZLCHH",
//       secretAccessKey: "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"
//   },
//   redashconfig: {
//     bucketName: "koovs-reports",
//     region: "ap-southeast-1",
//     accessKeyId: "AKIAWJMHT5ACYX5WVD67",
//     secretAccessKey: "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"
//   },
// };


module.exports = {
    ReferralApiUrl : "/jarvis-home-service/internal/v1/home/",
    courierServiceApiUrl: "http://a7c6a5e4a719e11e9b89502bb79d7e19-952630164.ap-southeast-1.elb.amazonaws.com:32510",
    poApiUrl: "http://52.172.182.183:9048",
    asnApiUrl: "http://52.172.182.183:9047",
    localApiUrl:
      "http://api-koovsmig-k8s-local-os6asb-919412082.ap-southeast-1.elb.amazonaws.com:31851",
    imageUrl: "https://s3-ap-southeast-1.amazonaws.com/img.koovs.com",
    cookiePrefix: "koovs",
    config: {
      bucketName: "img.koovs.com",
      sizeMapBucketName: "koovsimages/sizeguide",
      videoBucketName: "videos.koovs.cos3configm/catwalk",
      region: "ap-southeast-1",
      accessKeyId: "AKIAI5KORQD45VHUZJGQ",
      secretAccessKey: "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"
    },
    s3config: {
      bucketName: "img.koovs.com",
      region: "ap-southeast-1",
      accessKeyId: "AKIAWJMHT5ACVSF2E2BJ",
      secretAccessKey: "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"
  },
    accessTokenCookie: "AccessToken",
    refreshTokenCookie: "RefreshToken",
    cookieExpiryDays: "180",
    requestTimeoutKey: {
      DEFAULT: 15000,
      GET: 15000,
      POST: 15000,
      PUT: 15000,
      DELETE: 15000,
      GETUSERPROFILE: 15000
    },
    authApiBaseUrl: "http://authmg.koovs.com",
    env: "local",
    recordMessage: "No Record Found",
    taggingDevApi: "http://koovsmg-api.koovs.com",
    orderApiUrl: "http://koovsmg-api.koovs.com",
    ruleServiceApiUrl: "http://koovsmg-api.koovs.com",
    NewruleServiceApiUrl : "http://koovsmgcatalog.koovs.com/",
    baseUrl: "http://migration.koovs.com",
    pricingApiUrl: "http://koovsmgcatalog.koovs.com",
    //inventoryApiUrl: "http://13.228.158.178:9093",
    inventoryApiUrl: "http://koovsmgcatalog.koovs.com",
    vmApiDomain: "http://13.233.223.188",
    vendorId: "KOOVS",
    bsid: "e9fe04a841f5341698038b9d00a27fe7",
    courierApiUrl: "http://koovsmgcatalog.koovs.com",
    namespace: "koovs",
    PincodeServiceApiUrl: "http://koovsmg-api.koovs.com",
    HomeServiceApiUrl: "http://koovsmg-api.koovs.com",
    cdnUrl: "https://product.koovs.com/",
    jarvisListingUrl: "/jarvis-service/v1/product/listing?href=",
    APP_MAIL_LINK: "http://migration.koovs.com",
    WEB_MAIL_LINK: "http://migration.koovs.com",
    FROM_EMAIL: "support@koovs.com",
    IOS_DEEP_LINK: "koovs",
    newSearchService:"http://search-service-external.koovs.com:30353",
    ALLOWED_EMAIL_DOMAINS: /^\"?[\w-_\.]*\"?@koovs\.com$/,
    reportconfig: {
        bucketName: "data-dumps-analysis",
        region: "ap-southeast-1",
        accessKeyId: "AKIAYYR5X4KOSK7ZLCHH",
        secretAccessKey: "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"
    },
    redashconfig: {
      bucketName: "koovs-reports",
      region: "ap-southeast-1",
      accessKeyId: "AKIAWJMHT5ACYX5WVD67",
      secretAccessKey: "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"
    },
};


// module.exports = {
//   legacybaseurl: "http://alphagensoa.koovs.com",
//   poApiUrl: "http://52.172.182.183:9048",
//   asnApiUrl: "http://52.172.182.183:9047",
//   localApiUrl: "http://internal-koovs-migration-360017195.ap-southeast-1.elb.amazonaws.com:31851",
//   imageUrl: "https://s3-ap-southeast-1.amazonaws.com/img.koovs.com",
//  videoUrl: "https://s3-ap-southeast-1.amazonaws.com/videos.koovs.com",
//  cookiePrefix: "genesis",
//   config: {
//     bucketName: "img.koovs.com",
//     sizeMapBucketName: "koovsimages/uploads/templates",
//     videoBucketName: "videos.koovs.com/catwalk",
//     region: "ap-southeast-1",
//     accessKeyId: "AKIAWJMHT5ACVSF2E2BJ",
//     secretAccessKey: "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"
//   },
//   accessTokenCookie: "AccessToken",
//   refreshTokenCookie: "RefreshToken",
//   cookieExpiryDays: "180",
//   requestTimeoutKey: {
//     DEFAULT: 15000,
//     GET: 15000,
//     POST: 15000,
//     PUT: 15000,
//     DELETE: 15000,
//     GETUSERPROFILE: 15000
//   },
//   authApiBaseUrl: "http://internal-koovs-migration-360017195.ap-southeast-1.elb.amazonaws.com:30804",
//   env: "local",
//   recordMessage: "No Record Found",
//   taggingDevApi: "http://192.168.3.177:9096",
//   orderApiUrl: "http://jarvis.koovs-migration.internal",
//   ruleServiceApiUrl: "http://jarvis.koovs-migration.internal",
//   NewruleServiceApiUrl : "http://10.5.1.128:9191",
//   baseUrl: "https://migration.koovs.com",
//   pricingApiUrl:
//     "http://internal-koovs-migration-360017195.ap-southeast-1.elb.amazonaws.com:31047",
//   inventoryApiUrl: "http://internal-koovs-migration-360017195.ap-southeast-1.elb.amazonaws.com:32631",
// //    "http://internal-koovs-migration-360017195.ap-southeast-1.elb.amazonaws.com:32631",
//   host: "koovs-mgdb.cfcgqrtoyxfe.ap-southeast-1.rds.amazonaws.com",
//   port: 4000,
//   vmApiDomain: 'http://internal-koovs-migration-360017195.ap-southeast-1.elb.amazonaws.com:30353',
//   vendorId: "KOOVS",
//   bsid: "e9fe04a841f5341698038b9d00a27fe7",
//   courierApiUrl: "http://internal-koovs-migration-360017195.ap-southeast-1.elb.amazonaws.com:32510",
//   namespace: "koovs",
//   koovsLogoUrl: "https://images.koovs.com/uploads/koovs/logo.png",
//   HomeServiceApiUrl: "http://jarvis.koovs-migration.internal",
//   cdnUrl: "https://product.koovs.com/",
//   jarvisListingUrl: "/search-service/v1/products/listing/complete?href=",
//   APP_MAIL_LINK: "http://migration.koovs.com",
//   WEB_MAIL_LINK: "http://migration.koovs.com",
//   FROM_EMAIL: "support@koovs.com",
//   IOS_DEEP_LINK: "koovs",
//   ALLOWED_EMAIL_DOMAINS: /^\"?[\w-_\.]*\"?@koovs\.com$/,
//   ReferralApiUrl : "http://referral.koovs-migration.internal:32261",
//   courierServiceApiUrl: "http://courierservice.koovs-migration.internal:32510",
//   reportconfig: {
//       bucketNameReadash:"data_analytics_report",
//       bucketName: "data-dumps-analysis",
//       region: "ap-southeast-1",
//       accessKeyId: "AKIAYYR5X4KOSK7ZLCHH",
//       secretAccessKey: "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"
//   },
// tenantId:"koovs"
// };