import { namespace } from "./config";
export const orderDetailsHeader = [
  "Type",
  "Gateway",
  "Product Description",
  "Parent Order Id",
  "Order Id/Txn Id",
  "Purchase Date",
  "Status",
  "Quantity",
  "Price",
  "Selling Price",
  "Shipping Charge",
  "Shipping Recovery",
  "Shipping Refund",
  "Actual Paid",
  "Promo Code discount",
  "Promo Code",
  "Shipping Name",
  "Shipping Status",
  "Label",
  "Product Info",
  //"Warehouse",
  //"Cashback Status",
  "Replace/Exchange",
];
export const paymentMethodMeta = [
  { label: "Payment Method", value: "" },
  { label: "Online", value: 0 },
  { label: "COD", value: 1 },
];
export const warehouseMeta = [{ label: "Warehouse", value: "" }];
export const shippingStatusMeta = [
  { label: "Shipping Status", value: "" },
  { label: "Not Shipped", value: "0" },
  { label: "Shipped Successfully", value: "2" },
  { label: "Shipped Back Usable", value: "3" },
  { label: "Shipment Lost", value: "4" },
  { label: "Shipment Delivered", value: "5" },
  { label: "Shipped Back Unusable", value: "7" },
  { label: "Shipment Reverse Pickup", value: "8" },
  { label: "RTO usable", value: "11" },
  { label: "RTO unusable", value: "12" },
  { label: "Shipment reverse pickup usable", value: "13" },
  { label: "Shipment reverse pickup unusable", value: "14" },
];
const koovsShippingStatusMeta = [
  { label: "Shipped with no tracking no", value: "1" },
  { label: "Shipment Refused", value: "6" },
  { label: "Shipment Damage", value: "9" },
  { label: "Shipment Wrong", value: "10" },
  { label: "Shipment Cancelled", value: "15" },
  { label: "Found lost shipment usable", value: "16" },
  { label: "Found lost shipment unusable", value: "17" },
];
export const statusMeta = [
  { label: "Completed", value: "1" },
  { label: "Cancelled", value: "3" },
  { label: "Queued", value: "6" },
  { label: "Reship To User", value: "19" },
  {
    label: "Refund By PG",
    value: "20",
    alt: "REFUND BY PG Finance team yet to refund	",
  },
  { label: "Re-Ordered", value: "25" },
  { label: "Credit Memo Generated", value: "26" },
  { label: "Direct Cancel", value: "27" },
  { label: "Invoiced", value: "28" },
  {
    label: "Refund By Cash",
    value: "29",
    alt: "Refund By Cash Finance team yet to refund	",
  },
  { label: "Returned to QC Location", value: "31" },
  { label: "Customer Requested For Refund", value: "32" },
  { label: "Return Requested For Promocode", value: "33" },
  { label: "User to Exchange", value: "34" },
  { label: "Exchange Requested", value: "37" },
  { label: "On Hold", value: "38" },
  { label: "Return Requested for cash Refund", value: "40" },
  { label: "Unable Exchange Confirm", value: "41" },
  { label: "Cancellation Requested", value: "45" },
  { label: "Refund Pending", value: "46" },
  { label: "Started", value: "0" },
  { label: "Failed", value: "2" },
];
const koovsStatusMeta = [
  { label: "COD Pending Verification", value: "4" },
  { label: "Cheque Pending Verification", value: "4" },
  { label: "Payback Pending Verification", value: "14" },
  { label: "User Cancelled COD", value: "15" },
  { label: "Dispatch Cancelled", value: "16" },
  { label: "Dispatch Approved", value: "17" },
  { label: "User Self Cancelled", value: "18" },
  { label: "Refund By KOOVS", value: "21" },
  { label: "Refund By PROMO CODE", value: "22" },
  { label: "Refund By PAYBACK", value: "23" },
  { label: "Customer Care Cancelled", value: "24" },
  { label: "User to Replace", value: "35" },
  { label: "Returned to Customer", value: "36" },
  { label: "Exchange cancel", value: "39" },
];
export const shipingServiceMeta = [
  { label: "Shipping Service Name", value: "1" },
  { label: "Blue Dart", value: "3" },
  { label: "Delhivery", value: "8" },
  { label: "DHL express", value: "34" },
  { label: "Ecom Express", value: "19" },
  { label: "Family", value: "36" },
  { label: "FFPK", value: "39" },
  { label: "Holisol", value: "33" },
  { label: "Mamenta", value: "32" },
  { label: "Marble", value: "23" },
  { label: "PICKINGO", value: "29" },
  { label: "SCM For You", value: "21" },
  { label: "Shadowfax", value: "30" },
  { label: "XpressBees", value: "31" },
];
export const startedOrdersHeader = [
  "Parent Order Id",
  "Order Id",
  "Txn Id",
  "Type",
  "Product",
  "Purchase Date",
  "Status",
  "Quantity",
  "Price",
  "Selling Price",
  "Actual Paid",
  "Shipping Charges",
  "Promo Code discount",
  "Promo Code",
  "Action",
];
export const reversePickupHeader = [
  "Order Id",
  "Txn Id",
  "Type",
  "Product",
  "Purchase Date",
  "Status",
  "Quantity",
  "Price",
  "Selling Price",
  "Actual Paid",
  "Promo Code discount",
  "Shipment Details",
  "Action",
];
export const processRefundHeader = [
  "Parent Order Id",
  "Order Id",
  "Txn Id",
  "Type",
  "Product",
  "Purchase Date",
  "Quantity",
  "Price",
  "Selling Price",
  "Actual Paid",
  "Promo Code discount",
  "Shipment Details",
  "Current Status",
  "Move to Assign Refund",
  "Action",
];
export const pendingRefundHeader = [
  "Parent Order Id",
  "Order Id",
  "Txn Id",
  "Type",
  "Product",
  "Purchase Date",
  "Quantity",
  "Price",
  "Selling Price",
  "Actual Paid",
  "Promo Code discount",
  "Shipment Details",
  "Current Status",
  "Move to Assign Refund",
];
export const exchangeReplaceHeader = [
  "New Order Id",
  "New Txn Id",
  "Type",
  "Product",
  "Purchase Date",
  "Status",
  "Quantity",
  "Old Order Id",
  "Old Txn Id",
  //"Action1",
  "Action",
  "Return Ref No",
];
export const assignRefundOrderHeader = [
  "Select",
  "Parent Order Id",
  "Order Id",
  "Txn Id",
  "Type",
  "Product",
  "Purchase Date",
  "Status",
  "Quantity",
  "Price",
  "Selling Price",
  "Actual Paid",
  "Promo Code discount",
  "Shipment Details",
  //"Customer Return Remarks",
  "Action",
];
export const transactionHistoryMeta = [
  "Date",
  "Log",
  "Updated By",
  "Old Values",
  "New Values",
];
export const unusableShipmentOrderHeader = [
  "Order Id",
  "Txn Id",
  "Type",
  "Product",
  "Purchase Date",
  "Status",
  "Quantity",
  "Price",
  "Selling Price",
  "Actual Paid",
  "Promo Code discount",
  "Shipment Details",
  "Action",
];
export const ShipmentStatusUpdate = [
  "Order Id",
  "Txn Id",
  "Type",
  "Product",
  "Purchase Date",
  "Status",
  "Quantity",
  "Price",
  "Selling Price",
  "Actual Paid",
  "Promo Code discount",
  "Shipment Details",
  "Update Status",
];
export const txnStatusChangeOrderHeader = [
  "Select",
  "Order Id",
  "Txn Id",
  "Type",
  "Product",
  "Purchase Date",
  "Status",
  "Quantity",
  "Price",
  "Selling Price",
  "Actual Paid",
  "Promo Code discount",
  "Shipment Details",
  "Action",
];
export const returnExchangeSelfShipsOrderHeader = [
  "Order Id",
  "Txn Id",
  "Type",
  "Product",
  "Purchase Date",
  "Requested Date",
  "Status",
  "Quantity",
  "Price",
  "Selling Price",
  "Actual Paid",
  "Promo Code discount",
  "Action",
];
export const revertFTRefundStatusOrderHeader = [
  "Parent Order Id",
  "Order Id",
  "Txn Id",
  "Type",
  "Product",
  "Purchase Date",
  "Quantity",
  "Price",
  "Selling Price",
  "Actual Paid",
  "Promo Code discount",
  "Shipment Details",
  "Current Status",
  "Make FT yet to refund",
];
export const shippingDetailsHeader = [
  "#",
  "Txn Id",
  "User Details",
  "Phone",
  "Email",
  "Service",
  "Current Status",
  "Shipped Back Date",
  "Shipping Date",
];
export const CallCenterUserTableHeader = [
  "Id",
  "Username",
  "Email",
  "Phone",
  "Date created",
  "View / Edit",
];
export const UserAddressTableHeader = [
  "#",
  "Name",
  "Phone",
  "Mobile",
  "Email",
  "Address",
  "City",
  "State",
  "Country",
  "Zip",
  "Landmark",
  "Default",
];
export const UserPromoCodeTableHeader = [
  "#",
  "Code",
  "Description",
  "Status",
  "Txnid",
  "Validity",
  "Min. Amount",
  "Max. Amount",
  "Applicable Payment Methods",
  "Type",
  "Applicable Platform Type",
];
export const UserTxnDetailsTableHeader = [
  "#",
  "Type",
  "Gateway",
  "Parent Order Id",
  "Order Id/Txn ID",
  "Purchase Date",
  "Product Name",
  "Txn status",
  "Quantity",
  "Price",
  "Selling Price",
  "Actual Paid",
  "Promo Code discount",
  "Promo Code",
  "Shipment Details",
  "Action",
];
export const SearchPinCodeTableHeader = [
  "Pincode",
  "Shipping supported",
  "Cod supported",
  "Return Supported",
  "Date updated",
];
export const SerachCourierPinCodeTableHeader = [
  "Zipcode",
  "Courier",
  "Enabled",
  "Pickup Supported",
  "Return Priority",
];
export const OrderProcessSteps = [
  "Order Confirmed",
  "Order Packed",
  "Shipped",
  "In Transit",
  "In Progress",
];
export const TempCartHeader = ["Username", "Phone Number", "Cart Data"];
export const UploadTypeOptions = [
  { label: "Upload Type", value: "" },
  { label: "Discount", value: "discount" },
  { label: "Price", value: "price" },
  { label: "Price Scheduler", value: "scheduler" },
  { label: "Price Scheduler Revert", value: "schedulerRevert" },
];
export const PriceSchedulerTableMeta = [
  "Batch Id",
  "Product Id",
  "Line Id",
  "Sku Id",
  "Vendor Id",
  "Warehouse Id",
  "Lot Id",
  "MRP",
  "Selling Price",
  "Scheduled Selling Price",
  "Start Time",
  "End Time",
  "Updated By",
  "Date Created",
  "Date Updated",
];
export const PriceSchedulerFilterMeta = [
  { label: "Price", value: "SELLING" },
  { label: "Scheduled", value: "SCHEDULED" },
];
export const csvLabelMeta = {
  discount: `skuId,vendorId,lotId,warehouseId,mrp,percentage`,
  price: `skuId,vendorId,lotId,warehouseId,sellingPrice,mrp`,
  scheduler: `skuId,vendorId,lotId,warehouseId,price,startTime,endTime,RevertPrice`,
  schedulerRevert: `skuId`,
};
export const priceUploadUrl = {
  discount: {
    url: "/pricing/upload-percentage-price-file",
    name: "priceRequest",
  },
  price: { url: "/pricing/upload-fixed-price-file", name: "priceRequest" },
  scheduler: {
    url: "/pricing/upload-scheduled-price-file",
    name: "scheduledRequest",
  },
  schedulerRevert: {
    url: "/pricing/upload-revert-sku",
    name: "schedulerRevert",
  },
};
export const priceScheduleTableHeader =
  "skuId,vendorId,lotId,warehouseId,mrp,sellingPrice,price,createdBy,updatedBy,updatedDate,createdDate,startTime,endTime";
export const bulkCsvHeader = {
  cancel: ["orderid", "txnid", "reason"],
  move_file: ["txnid", "orderid", "remarks"],
  process_file: [
    "txnid",
    "orderid",
    "reference_number",
    "refund_date",
    "amount",
  ],
  revert: ["txnid", "orderid"],
  reverse: ["orderid", "txnid", "reason"],
  delivery: ["txnid", "docketno", "date"],
};
export const genderMeta = {
  1: "Male",
  2: "Female",
  3: "Other",
};
export const ReturnExchangeHeader = [
  "Order Id",
  "Txn Id",
  "Type",
  "Deal",
  "Option",
  "Quantity",
  "Status",
  "Purchase Date",
  "Shipping",
  "Action",
  "Override",
];
export const tagMappingCsvHeader = "productid,lineid,tagname,priority";
export const skuTagMappingCsvHeader = "skuid,lineid,tagname";
export const tagRemoveCsvHeader = "productid,lineid,tagname";
export const refundInfoListHeader = [
  "Order Id",
  "Txn Id",
  "Order Actual Amount (in Rs.)",
  "Refund Amount (in Rs.)",
  "Refund Method",
  "Gateway Refund Status",
  "Refund Status",
  "Refund Ref",
  "Payment Src",
  "Payment Dest",
  "Refund Retrial",
  "Refund Initiate Date",
  //"Modified Date"
];
export const orderPaymentInfoListHeader = [
  "Order Id",
  "Net Collectable (in Rs.)",
  "Order Total (in Rs.)",
  "Payment Gateway Id",
  "Payment Gateway TxnId",
  "Payment Line Amount (in Rs.)",
  "Payment Line Status",
  "Payment Type",
  "Refunded (in Rs.)",
];
export const skuDetailsHeader = [
  "#",
  "Product Id",
  "Sku Id",
  "Inventory in Stock",
  "Lot",
  "WareHouse",
  "Vendor",
];
export const tagUpdateInventoryCsvHeader = [
  "inventoryValue",
  "lotId",
  "operationType",
  "referenceId",
  "skuId",
  "vendorId",
  "warehouseId",
];
export const overrideInventoryCsvHeader = [
  "inventoryValue",
  "lotId",
  "referenceId",
  "skuId",
  "vendorId",
  "warehouseId",
];
export const batchUpdateCsvHeader = [
  "Product Id",
  "Master Category",
  "Parent Category",
  "Product Name",
  "Merchant Name",
  "HSN Code",
  "EAN/UTC Code",
  "Season",
  "Long Description",
  "Short Description",
  "Workflow",
  "Gender",
  "Brand Type",
  "Product Type",
  "COD Type",
  "Style Tips",
  "MC Code",
  "Type",
  "Fabric",
  "Specific Fabric",
  "Pattern",
  "Specific Pattern",
  "Neck",
  "Collar Style",
  "Sleeve Type",
  "Sleeve Length",
  "Cuff Style",
  "Closure Type",
  "Hemline",
  "Length",
  "Fit",
  "Embellishment",
  "Waistband",
  "Waist Type",
  "Fly Style",
  "Belt Loops",
  "Pockets",
  "Occasion",
  "Trends",
  "Feature 1",
  "Feature 2",
  "Feature 3",
  "Feature 4",
  "Additional Features",
  "Model Measurements",
  "Wash Care",
  "Disclaimer",
];
export const batchUpdateCsvSample = [
  {
    "Product Id": "ASAPPwyw654",
    "Master Category": "Apparels",
    "Parent Category": "Shirts",
    "Product Name": "Pineapple Patch Cold Shoulder T-Shirt",
    "Merchant Name": "FRL",
    "HSN Code": "6204",
    "EAN/UTC Code": "8907733098392",
    Season: "SS'18",
    "Long Description":
      "Perfectly designed for relaxed weekend outings is this lavender coloured T-shirt from DJ & C. Featuring self-heathered print all over and butterfly",
    "Short Description": "test short",
    Workflow: "INHOUSE",
    Gender: "GIRLS",
    "Brand Type": "Domestic",
    "Product Type": "Private Label",
    "COD Type": "No",
  },
];
if (namespace === "koovs") {
  statusMeta.push(...koovsStatusMeta);
  shippingStatusMeta.push(...koovsShippingStatusMeta);
}
export const skuStatusMeta = [
  { label: "Active", value: 2 },
  { label: "Inactive", value: 3 },
];

export const productStatus = ["LIVE", "INACTIVE", "DELISTED"];
export const pricingLogsHeader = [
  "Sku Id",
  "New Mrp",
  "New Selling Price",
  "Old Mrp",
  "Old Selling Price",
  "Vendor Id",
  "Lot Id",
  "Warehouse Id",
  "Created By",
  "Created On",
  "Updated By",
  "Updated On",
];
export const promoLogsHeader = [
  "Sku Id",
  "New Mrp",
  "New Selling Price",
  "Old Mrp",
  "Old Selling Price",
  "Vendor Id",
  "Lot Id",
  "Warehouse Id",
  "Created By",
  "Created On",
  "Updated By",
  "Updated On",
];
export const inventoryLogsHeader = [
  "Sku Id",
  "Vendor Id",
  "Warehouse Id",
  "Lot Id",
  "Inventory Count",
  "Delta Value",
  "Delta Type",
  "Created By",
  "Created On",
  "Platform",
  "Key",
];
export const pricingScheduledLogsHeader = [
  "Sku Id",
  "Selling Price",
  "Scheduled Price",
  "Start Time",
  "End Time",
  "Status",
  "Vendor Id",
  "Lot Id",
  "Warehouse Id",
  "Created By",
  "Created On",
  "Updated By",
  "Updated On",
];
export const taggingLogsHeader = [
  "Tag Name",
  "Line ID",
  "Updated By",
  "Log Date",
  "Logs",
];
export const outfitListHeader = [
  "Id",
  "Product Ids",
  "Gender",
  "Type",
  "Status",
  "Edit",
  "View",
];
export const productLogsHeader = [
  "Product Id",
  "Message",
  "Updated At",
  "Updated By",
  "Old Value",
  "New Value",
];
export const actionMeta = [
  { label: "DROP_DOWN", value: "DROP_DOWN" },
  { label: "PRODUCT_LISTING", value: "PRODUCT_LISTING" },
  { label: "BRANDS", value: "BRANDS" },
  { label: "MENHOME", value: "MENHOME" },
  { label: "WOMENHOME", value: "WOMENHOME" },
  { label: "ACCOUNT_ACTION", value: "ACCOUNT_ACTION" },
  { label: "WEB_VIEW", value: "WEB_VIEW" },
  { label: "BAG_ACTION", value: "BAG_ACTION" },
  { label: "CUSTOM_HOME", value: "CUSTOM_HOME" },
];
export const platformMeta = [
  { label: "WEB", value: "WEB" },
  { label: "MSITE", value: "MSITE" },
  { label: "ANDROID", value: "ANDROID" },
  { label: "IOS", value: "IOS" },
];
export const headerListMeta = [
  "Id",
  "Platform",
  "Status",
  "Active From",
  "Created Date",
  "Updated Date",
  "Created By",
  "Last Updated By",
  "Action",
];
export const listHeaderActionMeta = [
  "Action",
  "Copy",
  "Edit",
  "Delete",
  "Approve",
];
export const theme = {
  scheme: "monokai",
  base00: "#272822",
  base01: "#383830",
  base02: "#49483e",
  base03: "#75715e",
  base04: "#a59f85",
  base05: "#f8f8f2",
  base06: "#f5f4f1",
  base07: "#f9f8f5",
  base08: "#f92672",
  base09: "#fd971f",
  base0A: "#f4bf75",
  base0B: "#a6e22e",
  base0C: "#a1efe4",
  base0D: "#66d9ef",
  base0E: "#ae81ff",
  base0F: "#cc6633",
};
export const headerStatusMeta = [
  { label: "ACTIVE", value: "4" },
  { label: "INACTIVE", value: "1" },
  { label: "PENDING_REVIEW", value: "2" },
  // { label: "PENDING", value: "3" },
  // { label: "DELETED", value: "0" }
];

export const widgetListMeta = [
  "Name",
  "Type",
  "Version",
  // "Status",
  "Platforms",
  "Created On",
  "Created By",
  "Modified On",
  "Modified By",
  "Active From",
  // "Pages"
  // "Action",
];
export const widgetTypeMeta = [
  "BANNER",
  "PRODUCT",
  "HORIZONTAL_TILE_1",
  "HORIZONTAL_TILE_2",
  "HOTNOW",
  "VIDEO_BANNER",
  "STRIP_BANNER",
  "VERTICAL_TILE_1",
  "TEXT_BANNER",
  "SALE_TIMER",
  "FLEX_TILE",
  "GRID_TILE",
  "LOGO_STRIP",
  "BRAND_STORE",
  "SUBSCRIPTION",
  "SPACE_STRIP",
  "OVERLAP_TILE_2",
  // "SHOP_THE_LOOK",
  "VIDEO_N_IMAGE",
  "RECENT",
  "CART",  
  "ORDER_TRACK",
  "FLASH_SALE"
];
export const templateMeta = [
  "Title",
  "Category/Page Type",
  "Platfroms",
  // "Status",
  "VersionId",
  "Created On",
  "Created By",
  "Modified On",
  "Modified By",
  "Active From"
];
export const templateActionMeta = [
  "Action",
  "Edit",
  "Delete",
  "Preview",
  "Approve",
];
export const includedPlatforms = ["IOS", "ANDROID"];
export const includedActions = ["PRODUCT_LISTING"];
export const genderUrlMeta = [
  { label: "Unisex HP", value: "UNISEX" },
  { label: "Custom URL", value: "CUSTOM" },
  { label: "Men HP", value: "MEN" },
  { label: "Women HP", value: "WOMEN" },
];
export const sortByMeta = [
  { label: "NAME", value: "name" },
  { label: "ACTIVE DATE", value: "activeFrom" },
  { label: "CREATED DATE", value: "createdAt" },
  { label: "MODIFIED DATE", value: "updatedAt" }
];
export const sortOrderMeta = [
  { label: "Ascending", value: "asc" },
  { label: "Descending", value: "desc" },
];
export const listBannerMeta = [
  "Page url",
  "Start time",
  "End time",
  "Created Date",
  "Updated Date",
  "Created By",
  "Last Updated By",
  "Action",
];
export const allActionMeta = [
  "WOMEN_HOME",
  "PRODUCT_DISPLAY",
  "CATEGORY_LISTING",
  "PRODUCT_LISTING",
  "BRAND",
  "MEN_HOME",
  "VIDEO",
  "ACCOUNT",
  "WEB_VIEW",
  "DROP_DOWN",
  "BAG",
  "CUSTOM_HOME",
];
export const paymentBannerMeta = [
  "Start time",
  "End time",
  "Created Date",
  "Updated Date",
  "Created By",
  "Last Updated By",
  "Action",
];

export const modules = {
  toolbar: [
    [{ header: [1, 2, false] }],
    ["bold", "italic", "underline", "strike", "blockquote"],
    [
      { list: "ordered" },
      { list: "bullet" },
      { indent: "-1" },
      { indent: "+1" },
    ],
    ["link"],
    ["clean"],
  ],
  clipboard: {
    matchVisual: false,
  },
};
export const formats = [
  "header",
  "bold",
  "italic",
  "underline",
  "strike",
  "blockquote",
  "list",
  "bullet",
  "indent",
  "link",
  "image",
];
export const hsnMeta = [
  "HSN Code",
  "Low GST Percent",
  "High GST Percent",
  "Updated Date",
  "Created Date",
  "Updated By",
  "Action"
];

export const promoListMeta = [
  "#",
  "Promo code",
  "Type",
  "Start Date",
  "Expiry Date",
  "Action",
] ;