export const FETCH_ASN_LIST_START = "FETCH_ASN_LIST_START";
export const FETCH_ASN_LIST_SUCCESS = "FETCH_ASN_LIST_SUCCESS";
export const FETCH_ASN_LIST_FAILURE = "FETCH_ASN_LIST_FAILURE";
export const FETCH_ASN_DETAILS_START = "FETCH_ASN_DETAILS_START";
export const FETCH_ASN_DETAILS_SUCCESS = "FETCH_ASN_DETAILS_SUCCESS";
export const FETCH_ASN_DETAILS_FAILURE = "FETCH_ASN_DETAILS_FAILURE";
export const POST_ASN_DETAILS_START = "POST_ASN_DETAILS_START";
export const POST_ASN_DETAILS_SUCCESS = "POST_ASN_DETAILS_SUCCESS";
export const POST_ASN_DETAILS_FAILURE = "POST_ASN_DETAILS_FAILURE";
export const FETCH_PO_LIST_START = "FETCH_PO_LIST_START";
export const FETCH_PO_LIST_SUCCESS = "FETCH_PO_LIST_SUCCESS";
export const FETCH_PO_LIST_FAILURE = "FETCH_PO_LIST_FAILURE";
export const SIGNIN_USER_START = "SIGNIN_USER_START";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_FAILURE = "SIGNIN_USER_FAILURE";
export const SIGN_OUT_USER_START = "SIGN_OUT_USER_START";
export const SIGN_OUT_USER_SUCCESS = "SIGN_OUT_USER_SUCCESS";
export const SIGN_OUT_USER_FAILURE = "SIGN_OUT_USER_FAILURE";
export const FETCH_ASN_DETAILS_BYPO_START = "FETCH_ASN_DETAILS_BYPO_START";
export const FETCH_ASN_DETAILS_BYPO_SUCCESS = "FETCH_ASN_DETAILS_BYPO_SUCCESS";
export const FETCH_ASN_DETAILS_BYPO_FAILURE = "FETCH_ASN_DETAILS_BYPO_FAILURE";

//Action Type for Brands
export const FETCH_ALL_BRANDS_START = "FETCH_ALL_BRANDS_START";
export const FETCH_ALL_BRANDS_SUCCESS = "FETCH_ALL_BRANDS_SUCCESS";
export const FETCH_ALL_BRANDS_FAILURE = "FETCH_ALL_BRANDS_FAILURE";
export const FETCH_BRAND_DETAILS_START = "FETCH_BRAND_DETAILS_START";
export const FETCH_BRAND_DETAILS_SUCCESS = "FETCH_BRAND_DETAILS_SUCCESS";
export const FETCH_BRAND_DETAILS_FAILURE = "FETCH_BRAND_DETAILS_FAILURE";
export const POST_BRAND_START = "POST_BRAND_START";
export const POST_BRAND_SUCCESS = "POST_BRAND_SUCCESS";
export const POST_BRAND_FAILURE = "POST_BRAND_FAILURE";
export const PUT_BRAND_START = "PUT_BRAND_START";
export const PUT_BRAND_SUCCESS = "PUT_BRAND_SUCCESS";
export const PUT_BRAND_FAILURE = "PUT_BRAND_FAILURE";
export const PATCH_BRAND_START = "PATCH_BRAND_START";
export const PATCH_BRAND_SUCCESS = "PATCH_BRAND_SUCCESS";
export const PATCH_BRAND_FAILURE = "PATCH_BRAND_FAILURE";

//Action Type for Roles
export const FETCH_ALL_ROLES_START = "FETCH_ALL_ROLES_START";
export const FETCH_ALL_ROLES_SUCCESS = "FETCH_ALL_ROLES_SUCCESS";
export const FETCH_ALL_ROLES_FAILURE = "FETCH_ALL_ROLES_FAILURE";

//Action Type for Parent Category
export const FETCH_ALL_PCATS_START = "FETCH_ALL_PCATS_START";
export const FETCH_ALL_PCATS_SUCCESS = "FETCH_ALL_PCATS_SUCCESS";
export const FETCH_ALL_PCATS_FAILURE = "FETCH_ALL_PCATS_FAILURE";
export const FETCH_PCAT_DETAILS_START = "FETCH_PCAT_DETAILS_START";
export const FETCH_PCAT_DETAILS_SUCCESS = "FETCH_PCAT_DETAILS_SUCCESS";
export const FETCH_PCAT_DETAILS_FAILURE = "FETCH_PCAT_DETAILS_FAILURE";
export const POST_PCAT_START = "POST_PCAT_START";
export const POST_PCAT_SUCCESS = "POST_PCAT_SUCCESS";
export const POST_PCAT_FAILURE = "POST_PCAT_FAILURE";
export const PUT_PCAT_START = "PUT_PCAT_START";
export const PUT_PCAT_SUCCESS = "PUT_PCAT_SUCCESS";
export const PUT_PCAT_FAILURE = "PUT_PCAT_FAILURE";
export const PATCH_PCAT_START = "PATCH_PCAT_START";
export const PATCH_PCAT_SUCCESS = "PATCH_PCAT_SUCCESS";
export const PATCH_PCAT_FAILURE = "PATCH_PCAT_FAILURE";

//Action Type for Child Category
export const FETCH_ALL_CCATS_START = "FETCH_ALL_CCATS_START";
export const FETCH_ALL_CCATS_SUCCESS = "FETCH_ALL_CCATS_SUCCESS";
export const FETCH_ALL_CCATS_FAILURE = "FETCH_ALL_CCATS_FAILURE";
export const FETCH_CCAT_DETAILS_START = "FETCH_CCAT_DETAILS_START";
export const FETCH_CCAT_DETAILS_SUCCESS = "FETCH_CCAT_DETAILS_SUCCESS";
export const FETCH_CCAT_DETAILS_FAILURE = "FETCH_CCAT_DETAILS_FAILURE";
export const POST_CCAT_START = "POST_CCAT_START";
export const POST_CCAT_SUCCESS = "POST_CCAT_SUCCESS";
export const POST_CCAT_FAILURE = "POST_CCAT_FAILURE";
export const PUT_CCAT_START = "PUT_CCAT_START";
export const PUT_CCAT_SUCCESS = "PUT_CCAT_SUCCESS";
export const PUT_CCAT_FAILURE = "PUT_CCAT_FAILURE";
export const PATCH_CCAT_START = "PATCH_CCAT_START";
export const PATCH_CCAT_SUCCESS = "PATCH_CCAT_SUCCESS";
export const PATCH_CCAT_FAILURE = "PATCH_CCAT_FAILURE";

//Action Type for Attribute Type
export const FETCH_ALL_ATTRIBUTETYPES_START = "FETCH_ALL_ATTRIBUTETYPES_START";
export const FETCH_ALL_ATTRIBUTETYPES_SUCCESS =
  "FETCH_ALL_ATTRIBUTETYPES_SUCCESS";
export const FETCH_ALL_ATTRIBUTETYPES_FAILURE =
  "FETCH_ALL_ATTRIBUTETYPES_FAILURE";
export const FETCH_ATTRIBUTETYPE_DETAILS_START =
  "FETCH_ATTRIBUTETYPE_DETAILS_START";
export const FETCH_ATTRIBUTETYPE_DETAILS_SUCCESS =
  "FETCH_ATTRIBUTETYPE_DETAILS_SUCCESS";
export const FETCH_ATTRIBUTETYPE_DETAILS_FAILURE =
  "FETCH_ATTRIBUTETYPE_DETAILS_FAILURE";
export const POST_ATTRIBUTETYPE_START = "POST_ATTRIBUTETYPE_START";
export const POST_ATTRIBUTETYPE_SUCCESS = "POST_ATTRIBUTETYPE_SUCCESS";
export const POST_ATTRIBUTETYPE_FAILURE = "POST_ATTRIBUTETYPE_FAILURE";
export const PUT_ATTRIBUTETYPE_START = "PUT_ATTRIBUTETYPE_START";
export const PUT_ATTRIBUTETYPE_SUCCESS = "PUT_ATTRIBUTETYPE_SUCCESS";
export const PUT_ATTRIBUTETYPE_FAILURE = "PUT_ATTRIBUTETYPE_FAILURE";
export const PATCH_ATTRIBUTETYPE_START = "PATCH_ATTRIBUTETYPE_START";
export const PATCH_ATTRIBUTETYPE_SUCCESS = "PATCH_ATTRIBUTETYPE_SUCCESS";
export const PATCH_ATTRIBUTETYPE_FAILURE = "PATCH_ATTRIBUTETYPE_FAILURE";
export const FETCH_ALL_ENUM_START = "FETCH_ALL_ENUM_START";
export const FETCH_ALL_ENUM_SUCCESS = "FETCH_ALL_ENUM_SUCCESS";
export const FETCH_ALL_ENUM_FAILURE = "FETCH_ALL_ENUM_FAILURE";

//Action Type for Attribute Value
export const FETCH_ALL_ATTRIBUTEVALUES_START =
  "FETCH_ALL_ATTRIBUTEVALUES_START";
export const FETCH_ALL_ATTRIBUTEVALUES_SUCCESS =
  "FETCH_ALL_ATTRIBUTEVALUES_SUCCESS";
export const FETCH_ALL_ATTRIBUTEVALUES_FAILURE =
  "FETCH_ALL_ATTRIBUTEVALUES_FAILURE";
export const FETCH_ATTRIBUTEVALUE_DETAILS_START =
  "FETCH_ATTRIBUTEVALUE_DETAILS_START";
export const FETCH_ATTRIBUTEVALUE_DETAILS_SUCCESS =
  "FETCH_ATTRIBUTEVALUE_DETAILS_SUCCESS";
export const FETCH_ATTRIBUTEVALUE_DETAILS_FAILURE =
  "FETCH_ATTRIBUTEVALUE_DETAILS_FAILURE";
export const POST_ATTRIBUTEVALUE_START = "POST_ATTRIBUTEVALUE_START";
export const POST_ATTRIBUTEVALUE_SUCCESS = "POST_ATTRIBUTEVALUE_SUCCESS";
export const POST_ATTRIBUTEVALUE_FAILURE = "POST_ATTRIBUTEVALUE_FAILURE";
export const PUT_ATTRIBUTEVALUE_START = "PUT_ATTRIBUTEVALUE_START";
export const PUT_ATTRIBUTEVALUE_SUCCESS = "PUT_ATTRIBUTEVALUE_SUCCESS";
export const PUT_ATTRIBUTEVALUE_FAILURE = "PUT_ATTRIBUTEVALUE_FAILURE";
export const PATCH_ATTRIBUTEVALUE_START = "PATCH_ATTRIBUTEVALUE_START";
export const PATCH_ATTRIBUTEVALUE_SUCCESS = "PATCH_ATTRIBUTEVALUE_SUCCESS";
export const PATCH_ATTRIBUTEVALUE_FAILURE = "PATCH_ATTRIBUTEVALUE_FAILURE";

//Action Type for Products
export const FETCH_ALL_PRODUCTS_START = "FETCH_ALL_PRODUCTS_START";
export const FETCH_ALL_PRODUCTS_SUCCESS = "FETCH_ALL_PRODUCTS_SUCCESS";
export const FETCH_ALL_PRODUCTS_FAILURE = "FETCH_ALL_PRODUCTS_FAILURE";
export const FETCH_PRODUCT_DETAILS_START = "FETCH_PRODUCT_DETAILS_START";
export const FETCH_PRODUCT_DETAILS_SUCCESS = "FETCH_PRODUCT_DETAILS_SUCCESS";
export const FETCH_PRODUCT_DETAILS_FAILURE = "FETCH_PRODUCT_DETAILS_FAILURE";
export const POST_PRODUCT_START = "POST_PRODUCT_START";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const POST_PRODUCT_FAILURE = "POST_PRODUCT_FAILURE";
export const POST_PRODUCT_LIVE_START = "POST_PRODUCT_LIVE_START";
export const POST_PRODUCT_LIVE_SUCCESS = "POST_PRODUCT_LIVE_SUCCESS";
export const POST_PRODUCT_LIVE_FAILURE = "POST_PRODUCT_LIVE_FAILURE";
export const PUT_PRODUCT_START = "PUT_PRODUCT_START";
export const PUT_PRODUCT_SUCCESS = "PUT_PRODUCT_SUCCESS";
export const PUT_PRODUCT_FAILURE = "PUT_PRODUCT_FAILURE";
export const PATCH_PRODUCT_START = "PATCH_PRODUCT_START";
export const PATCH_PRODUCT_SUCCESS = "PATCH_PRODUCT_SUCCESS";
export const PATCH_PRODUCT_FAILURE = "PATCH_PRODUCT_FAILURE";
export const FETCH_ALL_METADATA_START = "FETCH_ALL_METADATA_START";
export const FETCH_ALL_METADATA_SUCCESS = "FETCH_ALL_METADATA_SUCCESS";
export const FETCH_ALL_METADATA_FAILURE = "FETCH_ALL_METADATA_FAILURE";
export const BATCH_PRODUCT_START = "BATCH_PRODUCT_START";
export const BATCH_PRODUCT_SUCCESS = "BATCH_PRODUCT_SUCCESS";
export const BATCH_PRODUCT_FAILURE = "BATCH_PRODUCT_FAILURE";

//Action Type for ProductsImage
export const FETCH_PRODUCT_IMAGE_START = "FETCH_PRODUCT_IMAGE_START";
export const FETCH_PRODUCT_IMAGE_SUCCESS = "FETCH_PRODUCT_IMAGE_SUCCESS";
export const FETCH_PRODUCT_IMAGE_FAILURE = "FETCH_PRODUCT_IMAGE_FAILURE";

export const FETCH_LINE_IMAGE_START = "FETCH_LINE_IMAGE_START";
export const FETCH_LINE_IMAGE_SUCCESS = "FETCH_LINE_IMAGE_SUCCESS";
export const FETCH_LINE_IMAGE_FAILURE = "FETCH_LINE_IMAGE_FAILURE";

export const POST_PRODUCT_IMAGE_START = "POST_PRODUCT_IMAGE_START";
export const POST_PRODUCT_IMAGE_SUCCESS = "POST_PRODUCT_IMAGE_SUCCESS";
export const POST_PRODUCT_IMAGE_FAILURE = "POST_PRODUCT_IMAGE_FAILURE";

export const UPLOAD_PRODUCT_IMAGE_START = "UPLOAD_PRODUCT_IMAGE_START";
export const UPLOAD_PRODUCT_IMAGE_SUCCESS = "UPLOAD_PRODUCT_IMAGE_SUCCESS";
export const UPLOAD_PRODUCT_IMAGE_FAILURE = "UPLOAD_PRODUCT_IMAGE_FAILURE";

export const REMOVE_ERROR = "REMOVE_ERROR";



//Product Logs
export const FETCH_PRODUCT_LOG_START = "FETCH_PRODUCT_LOG_START";
export const FETCH_PRODUCT_LOG_SUCCESS = "FETCH_PRODUCT_LOG_SUCCESS";
export const FETCH_PRODUCT_LOG_FAILURE = "FETCH_PRODUCT_LOG_FAILURE";


//Action Type for AddMeasurement
export const FETCH_ALL_MEASURES_START = "FETCH_ALL_MEASURES_START";
export const FETCH_ALL_MEASURES_SUCCESS = "FETCH_ALL_MEASURES_SUCCESS";
export const FETCH_ALL_MEASURES_FAILURE = "FETCH_ALL_MEASURES_FAILURE";
export const FETCH_MEASURE_DETAILS_START = "FETCH_MEASURE_DETAILS_START";
export const FETCH_MEASURE_DETAILS_SUCCESS = "FETCH_MEASURE_DETAILS_SUCCESS";
export const FETCH_MEASURE_DETAILS_FAILURE = "FETCH_MEASURE_DETAILS_FAILURE";
export const POST_MEASURE_START = "POST_MEASURE_START";
export const POST_MEASURE_SUCCESS = "POST_MEASURE_SUCCESS";
export const POST_MEASURE_FAILURE = "POST_MEASURE_FAILURE";
export const PUT_MEASURE_START = "PUT_MEASURE_START";
export const PUT_MEASURE_SUCCESS = "PUT_MEASURE_SUCCESS";
export const PUT_MEASURE_FAILURE = "PUT_MEASURE_FAILURE";
export const PATCH_MEASURE_START = "PATCH_MEASURE_START";
export const PATCH_MEASURE_SUCCESS = "PATCH_MEASURE_SUCCESS";
export const PATCH_MEASURE_FAILURE = "PATCH_MEASURE_FAILURE";

//Action Type for ProductsMeasure
export const FETCH_PRODUCT_MEASURE_START = "FETCH_PRODUCT_MEASURE_START";
export const FETCH_PRODUCT_MEASURE_SUCCESS = "FETCH_PRODUCT_MEASURE_SUCCESS";
export const FETCH_PRODUCT_MEASURE_FAILURE = "FETCH_PRODUCT_MEASURE_FAILURE";
export const POST_PRODUCT_MEASURE_START = "POST_PRODUCT_MEASURE_START";
export const POST_PRODUCT_MEASURE_SUCCESS = "POST_PRODUCT_MEASURE_SUCCESS";
export const POST_PRODUCT_MEASURE_FAILURE = "POST_PRODUCT_MEASURE_FAILURE";
export const REMOVE_ERROR_MEASURE = "REMOVE_ERROR_MEASURE";

//Action Type for Tagging
export const FETCH_TAGS_START = "FETCH_TAGS_START";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";
export const FETCH_TAGS_FAILURE = "FETCH_TAGS_FAILURE";
export const POST_TAG_START = "POST_TAG_START";
export const POST_TAG_SUCCESS = "POST_TAG_SUCCESS";
export const POST_TAG_FAILURE = "POST_TAG_FAILURE";
export const FETCH_TAG_BY_NAME_START = "FETCH_TAG_BY_NAME_START";
export const FETCH_TAG_BY_NAME_SUCCESS = "FETCH_TAG_BY_NAME_SUCCESS";
export const FETCH_TAG_BY_NAME_FAILURE = "FETCH_TAG_BY_NAME_FAILURE";
export const POST_CSV_START = "POST_CSV_START";
export const POST_CSV_SUCCESS = "POST_CSV_SUCCESS";
export const POST_CSV_FAILURE = "POST_CSV_FAILURE";
export const POST_SKU_CSV_START = "POST_SKU_CSV_START";
export const POST_SKU_CSV_SUCCESS = "POST_SKU_CSV_SUCCESS";
export const POST_SKU_CSV_FAILURE = "POST_CSV_FAILURE";
export const PATCH_TAG_START = "PATCH_TAG_START";
export const PATCH_TAG_SUCCESS = "PATCH_TAG_SUCCESS";
export const PATCH_TAG_FAILURE = "PATCH_TAG_FAILURE";
export const FETCH_FILE_STATUS_START = "FETCH_FILE_STATUS_START";
export const FETCH_FILE_STATUS_SUCCESS = "FETCH_FILE_STATUS_SUCCESS";
export const FETCH_FILE_STATUS_FAILURE = "FETCH_FILE_STATUS_FAILURE";
export const FETCH_TAG_MAPS_START = "FETCH_TAG_MAPS_START";
export const FETCH_TAG_MAPS_SUCCESS = "FETCH_TAG_MAPS_SUCCESS";
export const FETCH_TAG_MAPS_FAILURE = "FETCH_TAG_MAPS_FAILURE";
export const PUT_TAG_START = "PUT_TAG_START";
export const PUT_TAG_SUCCESS = "PUT_TAG_SUCCESS";
export const PUT_TAG_FAILURE = "PUT_TAG_FAILURE";

//Action Type for Order
export const FETCH_ORDER_LIST_START = "FETCH_ORDER_LIST_START";
export const FETCH_ORDER_LIST_SUCCESS = "FETCH_ORDER_LIST_SUCCESS";
export const FETCH_ORDER_LIST_FAILURE = "FETCH_ORDER_LIST_FAILURE";
export const POST_BULK_CSV_START =
  "POST_BULK_CSV_START";
export const POST_BULK_CSV_SUCCESS =
  "POST_BULK_CSV_SUCCESS";
export const POST_BULK_CSV_FAILURE =
  "POST_BULK_CSV_FAILURE";
export const PATCH_CRYPT_ORDER_START = "PATCH_CRYPT_ORDER_START";
export const PATCH_CRYPT_ORDER_SUCCESS = "PATCH_CRYPT_ORDER_SUCCESS";
export const PATCH_CRYPT_ORDER_FAILURE = "PATCH_CRYPT_ORDER_FAILURE";
export const FETCH_TXN_HISTORY_START = "FETCH_TXN_HISTORY_START";
export const FETCH_TXN_HISTORY_SUCCESS = "FETCH_TXN_HISTORY_SUCCESS";
export const FETCH_TXN_HISTORY_FAILURE = "FETCH_TXN_HISTORY_FAILURE";
export const FETCH_PROCESS_REFUND_START = "FETCH_PROCESS_REFUND_START";
export const FETCH_PROCESS_REFUND_SUCCESS = "FETCH_PROCESS_REFUND_SUCCESS";
export const FETCH_PROCESS_REFUND_FAILURE = "FETCH_PROCESS_REFUND_FAILURE";
export const POST_PROCESS_REFUND_START = "POST_PROCESS_REFUND_START";
export const POST_PROCESS_REFUND_SUCCESS = "POST_PROCESS_REFUND_SUCCESS";
export const POST_PROCESS_REFUND_FAILURE = "POST_PROCESS_REFUND_FAILURE";
export const FETCH_ASSIGN_REFUND_OS_START = "FETCH_ASSIGN_REFUND_OS_START";
export const FETCH_ASSIGN_REFUND_OS_SUCCESS = "FETCH_ASSIGN_REFUND_OS_SUCCESS";
export const FETCH_ASSIGN_REFUND_OS_FAILURE = "FETCH_ASSIGN_REFUND_OS_FAILURE";
export const POST_ASSIGN_REFUND_START = "POST_ASSIGN_REFUND_START";
export const POST_ASSIGN_REFUND_SUCCESS = "POST_ASSIGN_REFUND_SUCCESS";
export const POST_ASSIGN_REFUND_FAILURE = "POST_ASSIGN_REFUND_FAILURE";
export const POST_EXCHANGE_REPLACE_START = "POST_EXCHANGE_REPLACE_START";
export const POST_EXCHANGE_REPLACE_SUCCESS = "POST_EXCHANGE_REPLACE_SUCCESS";
export const POST_EXCHANGE_REPLACE_FAILURE = "POST_EXCHANGE_REPLACE_FAILURE";
export const FETCH_AVAILABLE_COURIERS_START = "FETCH_AVAILABLE_COURIERS_START";
export const FETCH_AVAILABLE_COURIERS_SUCCESS =
  "FETCH_AVAILABLE_COURIERS_SUCCESS";
export const FETCH_AVAILABLE_COURIERS_FAILURE =
  "FETCH_AVAILABLE_COURIERS_FAILURE";
export const POST_REVERSE_PICKUP_START = "POST_REVERSE_PICKUP_START";
export const POST_REVERSE_PICKUP_SUCCESS = "POST_REVERSE_PICKUP_SUCCESS";
export const POST_REVERSE_PICKUP_FAILURE = "POST_REVERSE_PICKUP_FAILURE";
export const POST_RPU_CANCELLED_START = "POST_RPU_CANCELLED_START";
export const POST_RPU_CANCELLED_SUCCESS = "POST_RPU_CANCELLED_SUCCESS";
export const POST_RPU_CANCELLED_FAILURE = "POST_RPU_CANCELLED_FAILURE";
export const POST_TXN_UPDATE_START = "POST_TXN_UPDATE_START";
export const POST_TXN_UPDATE_SUCCESS = "POST_TXN_UPDATE_SUCCESS";
export const POST_TXN_UPDATE_FAILURE = "POST_TXN_UPDATE_FAILURE";
export const FETCH_CRYPT_ORDER_START = "FETCH_CRYPT_ORDER_START";
export const FETCH_CRYPT_ORDER_SUCCESS = "FETCH_CRYPT_ORDER_SUCCESS";
export const FETCH_CRYPT_ORDER_FAILURE = "FETCH_CRYPT_ORDER_FAILURE";
export const POST_MOVE_TO_ASSIGN_REFUND_START =
  "POST_MOVE_TO_ASSIGN_REFUND_START";
export const POST_MOVE_TO_ASSIGN_REFUND_SUCCESS =
  "POST_MOVE_TO_ASSIGN_REFUND_SUCCESS";
export const POST_MOVE_TO_ASSIGN_REFUND_FAILURE =
  "POST_MOVE_TO_ASSIGN_REFUND_FAILURE";
export const FETCH_UNUSABLE_SHIPMENT_START = "FETCH_UNUSABLE_SHIPMENT_START";
export const FETCH_UNUSABLE_SHIPMENT_SUCCESS =
  "FETCH_UNUSABLE_SHIPMENT_SUCCESS";
export const FETCH_UNUSABLE_SHIPMENT_FAILURE =
  "FETCH_UNUSABLE_SHIPMENT_FAILURE";
export const PUT_UNUSABLE_SHIPMENT_START = "PUT_UNUSABLE_SHIPMENT_START";
export const PUT_UNUSABLE_SHIPMENT_SUCCESS = "PUT_UNUSABLE_SHIPMENT_SUCCESS";
export const PUT_UNUSABLE_SHIPMENT_FAILURE = "PUT_UNUSABLE_SHIPMENT_FAILURE";
export const POST_EXCHANGE_ORDER_START = "POST_EXCHANGE_ORDER_START";
export const POST_EXCHANGE_ORDER_SUCCESS = "POST_EXCHANGE_ORDER_SUCCESS";
export const POST_EXCHANGE_ORDER_FAILURE = "POST_EXCHANGE_ORDER_FAILURE";

export const PUT_UPDATE_SHIPMENT_START = "PUT_UPDATE_SHIPMENT_START";
export const PUT_UPDATE_SHIPMENT_SUCCESS = "PUT_UPDATE_SHIPMENT_SUCCESS";
export const PUT_UPDATE_SHIPMENT_FAILURE = "PUT_UPDATE_SHIPMENT_FAILURE";





//Actions for Temp Cart
export const FETCH_TEMP_CART_START = "FETCH_TEMP_CART_START";
export const FETCH_TEMP_CART_SUCCESS = "FETCH_TEMP_CART_SUCCESS";
export const FETCH_TEMP_CART_FAILURE = "FETCH_TEMP_CART_FAILURE";
export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const FETCH_PINCODE_START = "FETCH_PINCODE_START";
export const FETCH_PINCODE_SUCCESS = "FETCH_PINCODE_SUCCESS";
export const FETCH_PINCODE_FAILURE = "FETCH_PINCODE_FAILURE";
export const FETCH_REASONS_START = "FETCH_REASONS_START";
export const FETCH_REASONS_SUCCESS = "FETCH_REASONS_SUCCESS";
export const FETCH_REASONS_FAILURE = "FETCH_REASONS_FAILURE";

//Actions for Pricing
export const FETCH_SCHEDULED_PRICES_START = "FETCH_SCHEDULED_PRICES_START";
export const FETCH_SCHEDULED_PRICES_SUCCESS = "FETCH_SCHEDULED_PRICES_SUCCESS";
export const FETCH_SCHEDULED_PRICES_FAILURE = "FETCH_SCHEDULED_PRICES_FAILURE";


//Action Type for User Promo
export const FETCH_ALL_USER_PROMO_START = "FETCH_ALL_USER_PROMO_START";
export const FETCH_ALL_USER_PROMO_SUCCESS = "FETCH_ALL_USER_PROMO_SUCCESS";
export const FETCH_ALL_USER_PROMO_FAILURE = "FETCH_ALL_USER_PROMO_FAILURE";
export const FETCH_USER_PROMO_DETAILS_START = "FETCH_USER_PROMO_DETAILS_START";
export const FETCH_USER_PROMO_DETAILS_SUCCESS = "FETCH_USER_PROMO_DETAILS_SUCCESS";
export const FETCH_USER_PROMO_DETAILS_FAILURE = "FETCH_USER_PROMO_DETAILS_FAILURE";
export const POST_USER_PROMO_START = "POST_USER_PROMO_START";
export const POST_USER_PROMO_SUCCESS = "POST_USER_PROMO_SUCCESS";
export const POST_USER_PROMO_FAILURE = "POST_USER_PROMO_FAILURE";
export const POST_MULTIUSER_PROMO_START = "POST_MULTIUSER_PROMO_START";
export const POST_MULTIUSER_PROMO_SUCCESS = "POST_MULTIUSER_PROMO_SUCCESS";
export const POST_MULTIUSER_PROMO_FAILURE = "POST_MULTIUSER_PROMO_FAILURE";
export const PUT_USER_PROMO_START = "PUT_USER_PROMO_START";
export const PUT_USER_PROMO_SUCCESS = "PUT_USER_PROMO_SUCCESS";
export const PUT_USER_PROMO_FAILURE = "PUT_USER_PROMO_FAILURE";
export const PATCH_USER_PROMO_START = "PATCH_USER_PROMO_START";
export const PATCH_USER_PROMO_SUCCESS = "PATCH_USER_PROMO_SUCCESS";
export const PATCH_USER_PROMO_FAILURE = "PATCH_USER_PROMO_FAILURE";

//Action Type for Generic Promo
export const FETCH_ALL_GENERIC_PROMO_START = "FETCH_ALL_GENERIC_PROMO_START";
export const FETCH_ALL_GENERIC_PROMO_SUCCESS = "FETCH_ALL_GENERIC_PROMO_SUCCESS";
export const FETCH_ALL_GENERIC_PROMO_FAILURE = "FETCH_ALL_GENERIC_PROMO_FAILURE";
export const FETCH_GENERIC_PROMO_DETAILS_START = "FETCH_GENERIC_PROMO_DETAILS_START";
export const FETCH_GENERIC_PROMO_DETAILS_SUCCESS = "FETCH_GENERIC_PROMO_DETAILS_SUCCESS";
export const FETCH_GENERIC_PROMO_DETAILS_FAILURE = "FETCH_GENERIC_PROMO_DETAILS_FAILURE";
export const POST_GENERIC_PROMO_START = "POST_GENERIC_PROMO_START";
export const POST_GENERIC_PROMO_SUCCESS = "POST_GENERIC_PROMO_SUCCESS";
export const POST_GENERIC_PROMO_FAILURE = "POST_GENERIC_PROMO_FAILURE";
export const PUT_GENERIC_PROMO_START = "PUT_GENERIC_PROMO_START";
export const PUT_GENERIC_PROMO_SUCCESS = "PUT_GENERIC_PROMO_SUCCESS";
export const PUT_GENERIC_PROMO_FAILURE = "PUT_GENERIC_PROMO_FAILURE";
export const PATCH_GENERIC_PROMO_START = "PATCH_GENERIC_PROMO_START";
export const PATCH_GENERIC_PROMO_SUCCESS = "PATCH_GENERIC_PROMO_SUCCESS";
export const PATCH_GENERIC_PROMO_FAILURE = "PATCH_GENERIC_PROMO_FAILURE";

//Action Type for Promotional Promo
export const FETCH_ALL_PROMOTIONAL_PROMO_START = "FETCH_ALL_PROMOTIONAL_PROMO_START";
export const FETCH_ALL_PROMOTIONAL_PROMO_SUCCESS = "FETCH_ALL_PROMOTIONAL_PROMO_SUCCESS";
export const FETCH_ALL_PROMOTIONAL_PROMO_FAILURE = "FETCH_ALL_PROMOTIONAL_PROMO_FAILURE";
export const FETCH_PROMOTIONAL_PROMO_DETAILS_START = "FETCH_PROMOTIONAL_PROMO_DETAILS_START";
export const FETCH_PROMOTIONAL_PROMO_DETAILS_SUCCESS = "FETCH_PROMOTIONAL_PROMO_DETAILS_SUCCESS";
export const FETCH_PROMOTIONAL_PROMO_DETAILS_FAILURE = "FETCH_PROMOTIONAL_PROMO_DETAILS_FAILURE";
export const POST_PROMOTIONAL_PROMO_START = "POST_PROMOTIONAL_PROMO_START";
export const POST_PROMOTIONAL_PROMO_SUCCESS = "POST_PROMOTIONAL_PROMO_SUCCESS";
export const POST_PROMOTIONAL_PROMO_FAILURE = "POST_PROMOTIONAL_PROMO_FAILURE";
export const PUT_PROMOTIONAL_PROMO_START = "PUT_PROMOTIONAL_PROMO_START";
export const PUT_PROMOTIONAL_PROMO_SUCCESS = "PUT_PROMOTIONAL_PROMO_SUCCESS";
export const PUT_PROMOTIONAL_PROMO_FAILURE = "PUT_PROMOTIONAL_PROMO_FAILURE";
export const PATCH_PROMOTIONAL_PROMO_START = "PATCH_PROMOTIONAL_PROMO_START";
export const PATCH_PROMOTIONAL_PROMO_SUCCESS = "PATCH_PROMOTIONAL_PROMO_SUCCESS";
export const PATCH_PROMOTIONAL_PROMO_FAILURE = "PATCH_PROMOTIONAL_PROMO_FAILURE";

export const FETCH_MASTER_CATEGORY_START = "FETCH_MASTER_CATEGORY_START";
export const FETCH_MASTER_CATEGORY_SUCCESS = "FETCH_MASTER_CATEGORY_SUCCESS";
export const FETCH_MASTER_CATEGORY_FAILURE = "FETCH_MASTER_CATEGORY_FAILURE";
export const FETCH_SUB_CATEGORY_START = "FETCH_SUB_CATEGORY_START";
export const FETCH_SUB_CATEGORY_SUCCESS = "FETCH_SUB_CATEGORY_SUCCESS";
export const FETCH_SUB_CATEGORY_FAILURE = "FETCH_SUB_CATEGORY_FAILURE";
export const FETCH_BRAND_TEMPLATE_START = "FETCH_BRAND_TEMPLATE_START";
export const FETCH_BRAND_TEMPLATE_SUCCESS = "FETCH_BRAND_TEMPLATE_SUCCESS";
export const FETCH_BRAND_TEMPLATE_FAILURE = "FETCH_BRAND_TEMPLATE_FAILURE";
export const POST_TEMPLATE_IMAGE_START = "POST_TEMPLATE_IMAGE_START";
export const POST_TEMPLATE_IMAGE_SUCCESS = "POST_TEMPLATE_IMAGE_SUCCESS";
export const POST_TEMPLATE_IMAGE_FAILURE = "POST_TEMPLATE_IMAGE_FAILURE";
export const POST_SIZEMAP_DATA_START = "POST_SIZEMAP_DATA_START";
export const POST_SIZEMAP_DATA_SUCCESS = "POST_SIZEMAP_DATA_SUCCESS";
export const POST_SIZEMAP_DATA_FAILURE = "POST_SIZEMAP_DATA_FAILURE";

//Action Type for SEO
export const FETCH_ALL_SEOS_START = "FETCH_ALL_SEOS_START";
export const FETCH_ALL_SEOS_SUCCESS = "FETCH_ALL_SEOS_SUCCESS";
export const FETCH_ALL_SEOS_FAILURE = "FETCH_ALL_SEOS_FAILURE";
export const FETCH_SEO_DETAILS_START = "FETCH_SEO_DETAILS_START";
export const FETCH_SEO_DETAILS_SUCCESS = "FETCH_SEO_DETAILS_SUCCESS";
export const FETCH_SEO_DETAILS_FAILURE = "FETCH_SEO_DETAILS_FAILURE";
export const POST_SEO_START = "POST_SEO_START";
export const POST_SEO_SUCCESS = "POST_SEO_SUCCESS";
export const POST_SEO_FAILURE = "POST_SEO_FAILURE";
export const PUT_SEO_START = "PUT_SEO_START";
export const PUT_SEO_SUCCESS = "PUT_SEO_SUCCESS";
export const PUT_SEO_FAILURE = "PUT_SEO_FAILURE";
export const PATCH_SEO_START = "PATCH_SEO_START";
export const PATCH_SEO_SUCCESS = "PATCH_SEO_SUCCESS";
export const PATCH_SEO_FAILURE = "PATCH_SEO_FAILURE";


export const BATCH_PINCODE_PRODUCT_START = "BATCH_PINCODE_PRODUCT_START";
export const BATCH_PINCODE_PRODUCT_SUCCESS = "BATCH_PINCODE_PRODUCT_SUCCESS";
export const BATCH_PINCODE_PRODUCT_FAILURE = "BATCH_PINCODE_PRODUCT_FAILURE";


export const BATCH_SERVICABLE_PINCODE_PRODUCT_START = "BATCH_SERVICABLE_PINCODE_PRODUCT_START";
export const BATCH_SERVICABLE_PINCODE_PRODUCT_SUCCESS = "BATCH_SERVICABLE_PINCODE_PRODUCT_SUCCESS";
export const BATCH_SERVICABLE_PINCODE_PRODUCT_FAILURE = "BATCH_SERVICABLE_PINCODE_PRODUCT_FAILURE";